import heroKeyVisual from "../../public/media/vnext/hero-key-visual.png";

/**
 * Hero media layer.
 *
 * The homepage hero frame shows, in order of preference: an approved motion
 * clip framed for it (placement "hero-visual"), else the approved key-visual
 * still (`heroStill`). Rolling back from the clip to the still is one line:
 * set the clip's `approved` to false.
 *
 * WHY THIS IS NOT THE v0.1 PRESENTER SLOT
 * ---------------------------------------
 * v0.1 shipped `PresenterSlot.astro` backed by an empty `presenterAssets`
 * array. It rendered an empty box in the page flow — structure that produced
 * no pixels — and v0.2 correctly deleted it.
 *
 * This is a different shape of thing. The stage is fully designed and fully
 * rendered whether or not an asset exists here. An empty registry is not a
 * hole in the layout; it is the approved still alone, which is the design that
 * ships today. A registered asset does not add a new region, it repaints an
 * existing one. Nothing here can render an empty container.
 *
 * RULES
 * -----
 * 1. An asset appears on the site only after OWNER approval. `approved` is
 *    not a formality — an asset with `approved: false` is never rendered.
 * 2. Every asset states its own provenance. We do not ship media whose origin
 *    we cannot describe on the record.
 * 3. A poster still is mandatory. It is what mobile, reduced-motion, and slow
 *    connections actually see, so it is part of the asset, not an extra.
 * 4. The stage must remain readable with the media removed. Copy contrast is
 *    carried by the scrim, never by the footage.
 */

export type HeroMedia = {
  /** Stable id, used in the catalog and in the publication record. */
  id: string;
  /** Path under `public/`, served from the site origin. */
  src: string;
  /** Poster still at the same framing. Shown before play, on reduced motion, and on slow links. */
  poster: string;
  /** Intrinsic pixel size of the source. Used to reserve aspect ratio and avoid layout shift. */
  width: number;
  height: number;
  /**
   * Which side of the frame the subject occupies. The stage copy is placed on
   * the opposite side, so this drives the scrim direction rather than being
   * decorative metadata.
   */
  subjectSide: "left" | "right";
  /** Where the asset came from, on the record. */
  provenance: string;
  /** OWNER sign-off. Nothing renders without this. */
  approved: boolean;
  /**
   * Which hero layout the asset was framed for. Approval is per asset, fit is
   * per layout: an approved clip is not rendered in a layout it was not framed
   * for.
   */
  placement: HeroPlacement;
};

/**
 * - "full-bleed-stage": the v0.4 dark full-width stage, retired by the vNext
 *   homepage. Kept so the approved asset and its provenance stay on record.
 * - "hero-visual": the vNext hero's right-hand visual frame (16:10 on desktop,
 *   stacked under the copy on mobile). A clip here must be a 6–8s muted loop
 *   on a bright editorial ground, with Shiori small and supporting.
 */
export type HeroPlacement = "full-bleed-stage" | "hero-visual";

/**
 * The 9:16 Flow clips in the Shiori library are deliberately NOT registered
 * here. They are portrait 720x1280 raw captures held as vertical short-form
 * source; cropping one into a landscape hero would ship a low-resolution,
 * seam-looping portrait as a background it was never framed for. They stay
 * where they are, untouched.
 */
export const heroMediaLibrary: HeroMedia[] = [
  {
    id: "shiori-hero-16x9-v1",
    src: "/media/shiori-hero-16x9.mp4",
    poster: "/media/shiori-hero-16x9.jpg",
    width: 1920,
    height: 1080,
    subjectSide: "right",
    provenance:
      "Generated by the operator in Google Flow, 2026-09-09, as SHIORI_WEBSITE_HERO_16x9_V1 (1920x1080, 24fps, 8s). Chosen over V2 because V2's left third carries a lit desk lamp and two monitors that compete with the headline. Prepared for the web without touching the master: forward-then-reverse so the loop point is the same frame (loop-point PSNR 39.6dB against the master's 14.2dB), audio removed, re-encoded at CRF 30 for a layer that renders at 0.5 opacity behind a scrim.",
    approved: true,
    // Not re-used for vNext: a photoreal, full-frame presenter on a dark,
    // desaturated set. The vNext hero is a bright editorial canvas where
    // Shiori is a small navigator, so this clip would invert the hierarchy.
    placement: "full-bleed-stage"
  },
  {
    id: "vnext-hero-loop-v1",
    src: "/media/vnext/hero-loop.mp4",
    poster: "/media/vnext/hero-loop-poster.jpg",
    width: 1280,
    height: 720,
    subjectSide: "right",
    provenance:
      "OWNER-selected Google Flow clip, Drive SHIORI_MASTER_ASSETSwebsite/931371290_1790745061840991.mp4 (uploaded 2026-09-30; 1280x720, 24fps, 8.00s, H.264 High + AAC, 1.89 MB; sha256 135aa3e9...10bb42). Master copied byte-identical to media-src/vnext/hero-loop-original.mp4, outside public/ so it is never deployed. Web copy: audio removed, libx264 CRF 26 veryslow, 2s GOP, faststart, 590 KB, SSIM 0.993 / PSNR 48 dB against the master; not upscaled. Poster: the final frame (the decision state), 32 KB JPEG. No WebM: VP9 was not a meaningful saving at matching quality.",
    approved: true,
    placement: "hero-visual"
  }
];

/**
 * The hero's approved still: the key visual the frame shows on every device.
 * It is also what reduced motion and slow links see once a clip exists.
 *
 * The source file in `public/media/vnext/` is never altered. It is imported so
 * Astro's build (sharp, already an Astro dependency) emits right-sized AVIF and
 * WebP derivatives; the page never ships the 1.3 MB PNG.
 */

export type HeroStill = {
  image: ImageMetadata;
  /** The still carries Shiori and her "Start here." bubble, so it is content, not decoration. */
  alt: string;
  provenance: string;
  approved: boolean;
};

export const heroStill: HeroStill = {
  image: heroKeyVisual,
  alt: "Shiori, the site's guide, points past a cloud of scattered tool questions toward one clear, checked decision card.",
  provenance:
    "hero-key-visual.png, 1600x1000, added by OWNER as an approved vNext visual asset in commit 156f278 (2026-09-26).",
  approved: true
};

export function activeHeroStill(): HeroStill | null {
  return heroStill.approved ? heroStill : null;
}

/*
 * The frame's aspect ratio is set in CSS from the build-time media state
 * (16:9 with the clip, 16:10 with the still; 4:3 on phones), so the choice
 * never causes a layout shift.
 */

/** The asset a hero layout should render, or `null` to render its static visual alone. */
export function activeHeroMedia(placement: HeroPlacement = "hero-visual"): HeroMedia | null {
  return (
    heroMediaLibrary.find((asset) => asset.approved && asset.placement === placement) ?? null
  );
}
